// frontend/src/theme.js

export const lightTheme = {
  body: "#FFFFFF",
  text: "#000000",
  link: "#1E90FF",
  linkHover: "#1C6EA4",
  navbarBackground: "#F0F0F0",
  navbarText: "#333333",
  calendarBackground: "#FFFFFF",
  calendarText: "#333333",
  tileBackground: "#FFFFFF",
  tileText: "#333333",
  tileHoverBackground: "#E0E0E0",
  tileHoverText: "#000000",
  tileActiveBackground: "#1E90FF",
  tileActiveText: "#FFFFFF",
  tileCurrentBackground: "#ADD8E6", // Light blue for today's date
  tileCurrentText: "#000000",
  weekendText: "#FF0000",
  disabledBackground: "#F8F8F8",
  disabledText: "#A0A0A0",
  buttonBackground: "#007BFF",
  buttonText: "#FFFFFF",
  buttonHoverBackground: "#0056b3",
  buttonHoverText: "#FFFFFF",
  inputBackground: "#FFFFFF",
  inputText: "#333333",
  inputBorder: "#CCCCCC",
  inputFocusBorder: "#007BFF",
  highlightBackground: "#FFD700",
  highlightText: "#FFFFFF",
};

export const darkTheme = {
  body: "#121212",
  text: "#FFFFFF",
  link: "#BB86FC",
  linkHover: "#3700B3",
  navbarBackground: "#333333",
  navbarText: "#FFFFFF",
  calendarBackground: "#1E1E1E",
  calendarText: "#FFFFFF",
  tileBackground: "#333333",
  tileText: "#FFFFFF",
  tileHoverBackground: "#444444",
  tileHoverText: "#FFFFFF",
  tileActiveBackground: "#BB86FC",
  tileActiveText: "#FFFFFF",
  tileCurrentBackground: "#4A4A4A", // Darker shade for today's date
  tileCurrentText: "#FFFFFF",
  weekendText: "#FF5555",
  disabledBackground: "#2C2C2C",
  disabledText: "#555555",
  buttonBackground: "#BB86FC",
  buttonText: "#FFFFFF",
  buttonHoverBackground: "#3700B3",
  buttonHoverText: "#FFFFFF",
  inputBackground: "#333333",
  inputText: "#FFFFFF",
  inputBorder: "#555555",
  inputFocusBorder: "#BB86FC",
  highlightBackground: "#FF9800",
  highlightText: "#FFFFFF",
};
